name: PortMaster Release

on:
  push:
    paths-ignore:
      # - '.github/**'
      - 'README.md'
      - '.gitignore'

    branches:
      - main
      - master

  workflow_dispatch:

concurrency:
  group: release # only 1 release at a time

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:

      - uses: hmarr/debug-action@v2
        name: "debug: ${{github.event_name}}"

      - uses: actions/checkout@v2

      - name: env - better defaulting of env vars;
        id: env
        run: |
            source SOURCE_SETUP.txt

            if [[ -z "$RELEASE_ORG" ]]; then
              echo "::error file=SOURCE_SETUP.txt,line=2::Missing RELEASE_ORG, please configure"
              exit 255
            fi
            echo "RELEASE_ORG=$RELEASE_ORG" >> $GITHUB_OUTPUT

            if [[ -z "$RELEASE_REPO" ]]; then
              echo "::error file=SOURCE_SETUP.txt,line=5::Missing RELEASE_REPO, please configure"
              exit 255
            fi
            echo "RELEASE_REPO=$RELEASE_REPO" >> $GITHUB_OUTPUT

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Get release name for artifacts
        id: date
        run: |
            echo "date=$(date +'%Y-%m-%d_%H%M')" >> $GITHUB_OUTPUT

      - name: Create images zip from images Folder
        id: images-zip
        run: |
          find images \( -iname '*.jpg' -o  -iname '*.png' \) -exec touch -d '2021-01-01 00:00:00' {} \;
          find images \( -iname '*.jpg' -o  -iname '*.png' \) -exec chmod 644 {} \;
          find images \( -iname '*.jpg' -o  -iname '*.png' \) | sort | TZ=UTC zip -qX images.zip -@

      - name: Generate Port Files.
        id: ports-info
        run: |
          python3 tools/ports_json.py "${{steps.date.outputs.date}}"

      - name: "Prepare Release"
        uses: ncipollo/release-action@v1
        with:
          tag: "${{steps.date.outputs.date}}"
          allowUpdates: true
          draft: true
          prerelease: false
          replacesArtifacts: false
          omitNameDuringUpdate: true
          artifacts: "ports.md, ports.json, ports_status.json, *.source.json, *.zip, *.squashfs, *.md5"
          token: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ steps.env.outputs.RELEASE_REPO }}
          owner: ${{ steps.env.outputs.RELEASE_ORG }}

      - name: "Publish Release"
        uses: ncipollo/release-action@v1
        with:
          tag: "${{steps.date.outputs.date}}"
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          allowUpdates: true
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ steps.env.outputs.RELEASE_REPO }}
          owner: ${{ steps.env.outputs.RELEASE_ORG }}
      - name: Release Info
        id: info
        run: |
          echo "Published release: ${{steps.date.outputs.date}} to: https://github.com/${{ steps.env.outputs.RELEASE_ORG}}/${{ steps.env.outputs.RELEASE_REPO}}"
